Issue #2 renaming types
paffel2/echobot pull request #6
Opened 2021-09-16 11:40 UTC by paffel2

#2

2021-09-17 06:59 UTC, olgaklimenko commented
А можешь пулл реквест отредактировать, чтобы он был не ветку main а в issue#1-Pattern-Matching? И в остальных тоже сделать в ту ветку из которой создавал. Чтобы несолько раз одинаковые изменения не смотреть

2021-09-17 07:46 UTC, paffel2 commented
Сделал

2021-09-18 03:38 UTC, olgaklimenko commented on src/Telegram/Types.hs
> +type TelegramToken = String
Можешь рассказать, почему решил сделать синонимы типов, а не создать новые newtype?

2021-09-18 04:07 UTC, paffel2 commented on src/Telegram/Types.hs
> +type TelegramToken = String
Так на мой взгляд удобнее. Все равно для никакого дополнительного функционала для этих типов не предусмотрено. Можно было конечно обернуть все в ньютайп, но потом придется каждый раз вытаскивать данные и упаковывать. А так, просто использовать синонимы.

2021-09-18 04:33 UTC, olgaklimenko commented on src/Telegram/Types.hs
> +type TelegramToken = String
Но с ньютайп уменьшается вероятность перепутать местами два значения одного типа. 
Например, вот тут  `RepeatsList = [(ChatId,ReapeatsNum)]`, во время компиляции синонима уже не будет существовать и компилятор не заметит, что вместо `chatid` передан `reapeatsNum`. На практике чаще всего используется все-таки ньютайп. 

Синонимы, например, удобно использовать когда используется большой стек из трансформеров в сигнатурах.

2021-09-20 03:15 UTC, olgaklimenko requested changes

2021-09-20 03:15 UTC, olgaklimenko commented on src/Telegram/Types.hs
> +type TelegramToken = String
Лучше все-таки переделать на ньютайп)

2021-09-20 03:15 UTC, olgaklimenko commented on src/Telegram/Types.hs
> +type RepeatsList = [(ChatId,ReapeatsNum)]
Вот тут кстати пример, когда синоним можно оставить - синоним для списка. Список сам по себе является контейнером и мы задаём тип для внутренней структуры списка. Оборачивание в еще один слой не добавить смысла. 

А вот `chatId` и `repeatsNum` лучше все-таки сделать ньютайпами. Или еще вот так можно сделать:
`data Repeats = Repeats {chatId :: Int, num :: Int}`

2021-09-20 14:55 UTC, antonkalinin-ml commented on src/Telegram/Types.hs
> +type TelegramToken = String
> Все равно для никакого дополнительного функционала для этих типов не предусмотрено.

Дополнительного не предусмотрено, но не вся функциональность строк должна быть доступна для айдишников. Со строками можно делать много чего: склейку, поиск-замену, разделение, но для айдишника все эти операции не имеют смысла. Мы не склеиваем айдишники и не режем на части, мы только получаем их из телеги, храним и посылаем обратно, и нам неинтересно, что у них внутри. Поэтому по смыслу это отдельный тип, не совсем строка.

Что хуже, айдишников много и все они под капотом числа или строки. Очень легко перепутать и передать айдишник юзера туда, где требуется, например, айдишник сообщения. Когда же все айдишники имеют свои типы, ненароком этого не сделаешь, и сигнатура функции будет более говорящей.

2021-09-21 08:32 UTC, olgaklimenko requested changes

2021-09-21 08:32 UTC, olgaklimenko commented on src/Telegram/Types.hs
>  type HelpMessage = String
Не поняла уже готово исправление или нет, пора ли смотреть, но на всякий случай уточню, что комментарий про ньютайп относился не только к `TelegramToken`, а ко всем синонимам.

2021-09-21 10:39 UTC, paffel2 commented on src/Telegram/Types.hs
>  type HelpMessage = String
Теперь для телеграмма готово.

2021-09-22 04:01 UTC, olgaklimenko commented on src/Telegram/Types.hs
>  type HelpMessage = String
Да, это хорошая идея)

2021-09-23 04:56 UTC, olgaklimenko approved these changes

2021-09-23 05:00 UTC, olgaklimenko commented
перед тем как мержить в основную ветку, возможно надо будет конфликты зарезолвить:
![image](https://user-images.githubusercontent.com/11536292/134456498-7a1b55aa-3382-4d7f-a667-96d236cf9455.png)

Вот [тут](https://githowto.com/ru/resolving_conflicts) есть мини-инструкция как это сделать, или можно через vscode удобнее (если ты его используешь).

2021-09-23 05:40 UTC, merged